# vim: ft=yaml: sw=2:
#
log:
  destination: std::cerr 
  level: info 
  show-time: true 
  show-object: true

scopes:
  user:
    log:
      destination: file
      level: debug
      show-object: true
      show-pid: true
      show-time: false
      file: 
        location: logs
        size: 2K
        chunks: 3 
        use-pipe: true

    scopes:
      "sk::sys::User":
        log:
          show-time: true
          level:
            severity: none

  pty:
    log:
      destination: file
      level: debug
      time-format: %d-%H%M%S
      show-pid: true 
      show-time: true
      show-object: true
      file: 
        location: logs
        size: 3K 
        chunks: 4
        ensure-chunks: true
        policy: pointing
        use-pipe: false
